name = "ian-campaign"
pages_build_output_dir = "./dist"
compatibility_date = "2025-03-28"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_URL = "https://ian-campaign.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "ian-campaign-db"
database_id = "f524ab50-ee81-4091-9d34-811f56df165f"
migrations_dir = "src/lib/db/migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "516dae1aaa5b4ed3b82893e5725ea401"

